---
- hosts: all
  vars:
    is_centos: "'{{ ansible_distribution|lower }}' == 'centos'"
    is_debian: "'{{ ansible_distribution|lower }}' == 'debian'"
    is_ubuntu: "'{{ ansible_distribution|lower }}' == 'ubuntu'"
  vars_files:
    - "vars/{{ ansible_distribution|lower }}.yml"
  roles:
  - apache
  - nagios-src

